blank_issues_enabled: false
contact_links:
  - name: 🦆 byPixelTV's Discord
    url: https://dsc.gg/byPixelTV
    about: For general help with NoteSK join byPixelTV's Discord
  - name: 🚰 SkriptHub Docs
    url: https://skripthub.net/docs/?addon=NoteSK
    about: Read about NoteSK!